### ISSUE TITLE
support http server?

### ISSUE THREAD

**Issue by rdtan** [grpc-nebula/grpc-nebula-c#1]
### What version of gRPC and what language are you using?
 
 grpc  latest, and c++
### What operating system (Linux, Windows, …) and version?
 ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc version 4.9.2
 
### What did you do?
i have used the examples grpc-nebula provided well, but i am puzzled with how to build my grpc-gateway like in c++.
 
### What did you expect to see?
 since grpc c++ has not supported http server, only http client can not be enough, it would be very nice to see that we can build up our own grpc http server, and grpc has well  support http server in the go language.

in my scene, we depend http service to fetch business data, token, for instance. 
 
### What did you see instead?
 there is another implementation but in go language : https://github.com/grpc-ecosystem/grpc-gateway, we donot consider it because we want to make all services have the own entrance by zookeeper(grpc-nebula has provided yet), we cannot maintain another http-gateway, otherwise, the project is becoming larger and larger.

 
### Anything else we should know about your project / environment?
no more info can be provided....

**Comment by magicyang168** [comment]
just protobuf supported, maybe consider and investigate it later
