### ISSUE TITLE
I compiled according to the Linux document, but I didn't find the file grpc-c / LIBS / opt. I didn't find it in my cloned code!

### ISSUE THREAD

**Issue by white-black-hong** [grpc-nebula/grpc-nebula-c#2]

**Comment by magicyang168** [comment]
$ git clone -b RELEASExxxxx https://github.com/grpc-nebula/grpc-nebula-c
 $ cd grpc-nebula-c
 $ **git submodule update --init**

**Comment by white-black-hong** [comment]
Releaseexxxx this is the branch name? If not, where to get the right branch? @magicyang168

**Comment by white-black-hong** [comment]
Releaseexxxx this is the branch name? If not, where to get the right branch? @magicyang168

**Comment by magicyang168** [comment]
@white-black-hong   yes,  use "-b <branch-or-tag-or-commit> " for some version download. tag can also be okay.

**Comment by white-black-hong** [comment]
Hello, because the command "git submodule update --init" always makes mistakes and cannot be compiled successfully. I found the required library files through "git submodule init" and downloaded them one by one with the command. 

**Download library file**
git submodule add https://github.com.cnpmjs.org/abseil/abseil-cpp abseil-cpp 
git submodule add https://github.com.cnpmjs.org/google/benchmark benchmark
git submodule add https://github.com.cnpmjs.org/google/bloaty.git bloaty
git submodule add https://github.com.cnpmjs.org/google/boringssl.git boringssl
git submodule add https://github.com.cnpmjs.org/google/boringssl.git boringssl-with-bazel
git submodule add https://github.com.cnpmjs.org/c-ares/c-ares.git cares/cares
git submodule add https://github.com.cnpmjs.org/envoyproxy/data-plane-api.git data-plane-api
git submodule add https://github.com.cnpmjs.org/gflags/gflags.git gflags
git submodule add https://github.com.cnpmjs.org/googleapis/googleapis.git googleapis
git submodule add https://github.com.cnpmjs.org/google/googletest.git googletest
git submodule add https://github.com.cnpmjs.org/llvm-mirror/libcxx.git libcxx
git submodule add https://github.com.cnpmjs.org/llvm-mirror/libcxxabi.git libcxxabi
git submodule add https://github.com.cnpmjs.org/google/protobuf.git protobuf
git submodule add https://github.com.cnpmjs.org/lyft/protoc-gen-validate.git protoc-gen-validate
git submodule add https://github.com.cnpmjs.org/madler/zlib zlib

However, we did not get “开发代码编译”、“原生库拷贝” and “protobuf库拷贝” the required "lib" and "bins" files
![image](https://user-images.githubusercontent.com/68105775/87635809-440b1e80-c772-11ea-8f5b-b50f11cf7234.png)
![image](https://user-images.githubusercontent.com/68105775/87635875-58e7b200-c772-11ea-92f2-bd3496dcb748.png)
@magicyang168

**Comment by magicyang168** [comment]
sorry ,i found the problem,  was that leaking of compilation manual of grpc and our libs. the manual present was how to dev your application based on the SDKs.  will update it later, thanks for your question. ^v^
