### ISSUE TITLE
orientsec_provider_intf.cc的代码bug

### ISSUE THREAD

**Issue by hmilylzs** [grpc-nebula/grpc-nebula-c#3]
orientsec_provider_intf.cc文件的522行：
    url_t* router_url = NULL;
    bool acc = false;
    if (provider->access_protected) {
      **url_t* router_url =**
          url_for_router_from_param(provider->host, provider->sInterface);
      acc = true;
    } 

其中**url_t* router_url =**在if语句中重新进行了定义，导致后边529行：
std::thread zk_registry_agent_thread(grpc_provider_zk_registry_bg,
                                         pro_url,router_url,
                                         port,ver,acc);
中的router_url内容为NULL

**Comment by magicyang168** [comment]
Thanks for your concern. "router_url " was redefined, i'll fix it. on our business logic, router url was null is allowed, actully, it was used when acc = true in new thread.

**Comment by magicyang168** [comment]
I suppose your question was that router_url may be changed when new thread running, but new thread used just a copy of router_url.

**Comment by hmilylzs** [comment]
> Thanks for your concern. "router_url " was redefined, i'll fix it. on our business logic, router url was null is allowed, actully, it was used when acc = true in new thread.

谢谢关注与回复！
